### ISSUE TITLE
Double free of PooledStringBuilder

### ISSUE THREAD

**Issue by mrward** [mrward/vsmac-addin-compat#1]
Failed assertion: freeing twice?
   at MonoDevelop.Core.PooledObjects.ObjectPool`1.Validate(System.Object obj) in main/src/core/MonoDevelop.Core/MonoDevelop.Core.PooledObjects/ObjectPool.cs:line 283
   at MonoDevelop.Core.PooledObjects.ObjectPool`1.Free(MonoDevelop.Core.PooledObjects.T obj) in main/src/core/MonoDevelop.Core/MonoDevelop.Core.PooledObjects/ObjectPool.cs:line 205
   at MonoDevelop.Core.PooledObjects.PooledStringBuilder.Dispose() in main/src/core/MonoDevelop.Core/MonoDevelop.Core.PooledObjects/PooledStringBuilder.cs:line 64
   at Microsoft.VisualStudioMac.ExtensionCompatibility.CompatibilityCheckRunner.GetIncompatibleAddinInfo(System.Collections.Generic.List`1 incompatibleAddins)
   at Microsoft.VisualStudioMac.ExtensionCompatibility.CompatibilityCheckRunner+<RunCheckAsync>d__0.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(System.Threading.Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(System.Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(System.Threading.Tasks.TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(System.Threading.Tasks.Task`1 task, System.Runtime.CompilerServices.TResult result)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetResult(System.Runtime.CompilerServices.TResult result)
   at Microsoft.VisualStudioMac.ExtensionCompatibility.CompatibilityCheckRunner+<RunCheckAsync>d__6.MoveNext()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1.MoveNext(System.Threading.Thread threadPoolThread)
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(System.Object continuationObject)
   at System.Threading.Tasks.Task`1.TrySetResult(System.Threading.Tasks.TResult result)
   at System.Threading.Tasks.TaskCompletionSource`1.TrySetResult(System.Threading.Tasks.TResult result)
   at MonoDevelop.Core.Execution.ProcessWrapper.OnProcessWrapperExited() in main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/ProcessWrapper.cs:line 148
   at MonoDevelop.Core.Execution.ProcessWrapper.OnExited(System.Object sender, System.EventArgs args) in main/src/core/MonoDevelop.Core/MonoDevelop.Core.Execution/ProcessWrapper.cs:line 136
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Diagnostics.Process.CompletionCallback(System.Object waitHandleContext, Boolean wasSignaled)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state)
   at System.Threading.PortableThreadPool.CompleteWait(System.Threading.RegisteredWaitHandle handle, Boolean timedOut)
   at System.Threading.ThreadPoolWorkQueue.DispatchItemWithAutoreleasePool(System.Object workItem, System.Threading.Thread currentThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

**Comment by mrward** [comment]
Might not be an addin bug.

**Comment by mrward** [comment]
Code is disposing and freeing the string builder.

https://github.com/mrward/vsmac-addin-compat/blob/5e571c5af95fc35ef11661598c07dc0ac74481ea/src/ExtensionCompatibilityChecker/Microsoft.VisualStudioMac.ExtensionCompatibility/CompatibilityCheckRunner.cs#L196-L211
